version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: abhinav
          POSTGRES_PASSWORD: password
          POSTGRES_DB: webapp
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: npx sequelize-cli db:migrate
      - run: npm test