version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:9.3.0
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: thumbnail
    