version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: thumbnail
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }
      - run:
          name: Set Up DB
          command: |
            knex migrate:latest
            knex seed:running_man
      - run: npm test