version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: "abhinav"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "webapp"
    steps:
      - checkout
      - run: cp ormconfig.circleci-common.json ormconfig.json
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test