version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: thumbnail
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: psql postgres -c "CREATE ROLE ubuntu WITH PASSWORD 'ubuntu';"
      - run: psql postgres -c "alter user ubuntu with superuser;"
      - run: psql postgres -c "create database test;"
      - run:
          name: Set Up DB
          command: |
            knex migrate:latest
            knex seed:run
      - run: npm test